services:
  nextjs-website:
    build:
      context: .
      args:
        - NEXT_PUBLIC_COMPANY_NAME=${NEXT_PUBLIC_COMPANY_NAME}
        - NEXT_PUBLIC_CONTACT_FORM_KEY=${NEXT_PUBLIC_CONTACT_FORM_KEY}
        - KLANT_ID=${KLANT_ID}
        - LANNIE_API_URL=${LANNIE_API_URL}
    container_name: website-carestonesolutions
    restart: unless-stopped
    ports:
      - "3006:3000"
