FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

ARG NEXT_PUBLIC_COMPANY_NAME
ARG NEXT_PUBLIC_CONTACT_FORM_KEY
ARG KLANT_ID
ARG LANNIE_API_URL

ENV NEXT_PUBLIC_COMPANY_NAME=$NEXT_PUBLIC_COMPANY_NAME
ENV NEXT_PUBLIC_CONTACT_FORM_KEY=$NEXT_PUBLIC_CONTACT_FORM_KEY
ENV KLANT_ID=$KLANT_ID
ENV LANNIE_API_URL=$LANNIE_API_URL


RUN npm run build

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "start"]